FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Legacy@ZPS

API for One OPS

# Group API - Parcel
## Create Parcel [/api/legacy/parcel]
### POST [POST]

Import an **Array** of [**Parcel**](#reference/model-parcel) Objects and process them into shipments.

The shipments can be of any combination of accepted service types.

### Requested Parameters

**Array** of [**Parcel**](#reference/model-parcel) Models


### Response

#### HTTP 200 : Success
+ An **Array** of [**CreateShipmenResult**](#reference/model-createshipmentresult) Models


#### HTTP 400 : Failure
+ Signals that Input was Badly Formatted


#### HTTP 401 : Failure
+ Signals that Authentication Failed